### ISSUE TITLE
[ReportIt] Show TOP10 graphs error

### ISSUE THREAD

**Issue by omse974** [Cacti/plugin_reportit#110]
**Describe the bug**
In ReportIt plugin, a bug appear when I activate "Show TOP10 graphs" in "Console>Public Reports>Show Report".

**Screenshots**
![reportit-show_top10_grahs_error](https://github.com/Cacti/plugin_reportit/assets/70309992/75859b33-761a-4ca6-8214-2310173d69f9)
![reportit-realm](https://github.com/Cacti/plugin_reportit/assets/70309992/348affa3-9993-4a98-8313-5e4d379adc0e)
![reportit-show_top10_graphs](https://github.com/Cacti/plugin_reportit/assets/70309992/0d24408b-9d1b-496e-8b75-ce623e607074)

**Expected behavior**
An error message appear and the plugin is deactivated.
Then we must to uninstall and reinstall the plugin.
In the plugin_realms table, we see a charts.php file which is not present in the plugin installation file.
It might be the cause of this issue ?

**Plugin ReportIt:**
 - Version: 1.1.3
 - Source: github
 - Identifer: [9a8f992](https://github.com/Cacti/plugin_reportit/commit/9a8f992678aa66f5143dc6e3fb297e02e4cc17ce)

**Desktop:**
 - OS: Ubuntu 22.04.4 LTS
 - Browser : Firefox
 - Version : 125.0

**Comment by TheWitness** [comment]
Anything in the Cacti log?

**Comment by omse974** [comment]
Here, you find the Cacti log.

2024-04-15 07:40:19 - ERROR PHP ERROR in  Plugin 'reportit': Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /srv/cacti/plugins/reportit/view.php:919 Stack trace: #0 /srv/cacti/plugins/reportit/view.php(919): abs() #1 /srv/cacti/plugins/reportit/view.php(743): show_graph_view() #2 /srv/cacti/plugins/reportit/view.php(47): show_report() #3 {main} thrown in file: /srv/cacti/plugins/reportit/view.php on line: 919
2024-04-15 07:40:19 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2024-04-15 07:40:19 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'reportit'
2024-04-15 07:40:19 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
2024-04-15 07:40:20 - CMDPHP WARNING: Page:view.php?action=show_report&header=false&id=1&filter=&info=-2&rows=-1&measurand=-1&data_source=-1&archive=-1&graph_mode=on&summary=&subhead= Generated a Fatal Error:500
2024-04-15 07:40:20 - CMDPHP ERROR: debounce key was truncated from debounce_page_error_view.php?action=show_report&header=false&id=1&filter=&info=-2&rows=-1&measurand=-1&data_source=-1&archive=-1&graph_mode=on&summary=&subhead= to debounce_page_error_view.php?action=show_report&he Backtrace:  (/help.php[37]:debounce_run_notification(), /lib/functions.php[7328]:cacti_debug_backtrace())
2024-04-15 07:40:20 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
